// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTW5qHgRiDZlkme9IBCqxn-Qm13NFBaVo',
    appId: '1:161575002024:web:b34019942fef81eb2b879d',
    messagingSenderId: '161575002024',
    projectId: 'spendly-36477',
    authDomain: 'spendly-36477.firebaseapp.com',
    storageBucket: 'spendly-36477.firebasestorage.app',
    measurementId: 'G-VNQB26D2Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBol617ccrvg1TC0uGR6Z2jMZM5ckrSNaY',
    appId: '1:161575002024:android:983fe1e7c601c9b32b879d',
    messagingSenderId: '161575002024',
    projectId: 'spendly-36477',
    storageBucket: 'spendly-36477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJcLjE1L237ffzHPEkY6vMWncd0oaiso',
    appId: '1:161575002024:ios:7df70ca0bc9016db2b879d',
    messagingSenderId: '161575002024',
    projectId: 'spendly-36477',
    storageBucket: 'spendly-36477.firebasestorage.app',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJcLjE1L237ffzHPEkY6vMWncd0oaiso',
    appId: '1:161575002024:ios:7df70ca0bc9016db2b879d',
    messagingSenderId: '161575002024',
    projectId: 'spendly-36477',
    storageBucket: 'spendly-36477.firebasestorage.app',
    iosBundleId: 'com.example.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTW5qHgRiDZlkme9IBCqxn-Qm13NFBaVo',
    appId: '1:161575002024:web:12204b8c4d3014202b879d',
    messagingSenderId: '161575002024',
    projectId: 'spendly-36477',
    authDomain: 'spendly-36477.firebaseapp.com',
    storageBucket: 'spendly-36477.firebasestorage.app',
    measurementId: 'G-B7PEY7HWC3',
  );
}
